import type { Metadata } from 'next';
import { Session } from 'next-auth';
import { Inter } from 'next/font/google';

import { SessionProvider } from '@/components/nextAuth/SessionProvider';

import './globals.css';
import { ThemeProvider } from 'next-themes';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Financial Controller',
  description: 'Generated by create next app',
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>,
  session: Session | null | undefined,
) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <SessionProvider session={session}>
          <ThemeProvider defaultTheme="dark" attribute="class" themes={['light', 'dark']}>
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
