import { Session } from 'next-auth';
import { Inter } from 'next/font/google';

import { SessionProvider } from '@/components/nextAuth/SessionProvider';

import './globals.css';
import { ThemeProvider } from 'next-themes';

import { AI } from './ai';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Financial Controller',
  description: 'Generated by create next app',
  generator: 'Next.js',
  manifest: '/manifest.json',
  keywords: ['nextjs', 'nextjs14', 'next14', 'pwa', 'next-pwa'],
  themeColor: [{ media: '(prefers-color-scheme: dark)', color: '#232323' }],
  viewport:
    'minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover',
  icons: [
    { rel: 'apple-touch-icon', url: '/logo180x180.png' },
    { rel: 'icon', url: '/logo180x180.png' },
  ],
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>,
  session: Session | null | undefined,
) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title as string}</title>
        <meta name="description" content={metadata.description as string} />
        <meta name="generator" content={metadata.generator as string} />
        <link rel="manifest" href={metadata.manifest as string} />
        <meta name="keywords" content={metadata.keywords.join(', ')} />
        {metadata.themeColor.map(({ media, color }, index) => (
          <meta key={index} name="theme-color" media={media} content={color} />
        ))}
        <meta name="viewport" content={metadata.viewport} />
        {metadata.icons.map(({ rel, url }, index) => (
          <link key={index} rel={rel} href={url} />
        ))}
      </head>
      <body className={`${inter.className}`}>
        <SessionProvider session={session}>
          <ThemeProvider defaultTheme="dark" attribute="class" themes={['light', 'dark']}>
            <AI>{children}</AI>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
